# Generated by Django 4.2.16 on 2024-11-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
