# Generated by Django 4.2.16 on 2024-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_article_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
