# Generated by Django 4.2.16 on 2024-11-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_backdrop_url'),
        ('communities', '0007_article_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='movies.movie'),
        ),
    ]
