# Generated by Django 4.2.16 on 2024-11-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0004_categorymovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='movies',
            field=models.ManyToManyField(related_name='categories', to='movies.movie'),
        ),
    ]
