# Generated by Django 4.2.16 on 2024-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
