# Generated by Django 4.2.16 on 2024-11-24 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_release_date'),
        ('accounts', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_by', to='movies.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_movie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
