# Generated by Django 4.2.16 on 2024-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('vote_avg', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=500, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('actors', models.TextField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
